---
- name: Implementing CI-CD process
  hosts: all
  tasks:
   - name: Installing s/w
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk, b: yes }
      - {a: git, b: no}
      - {a: maven, b: no}
      - {a: tomcat9, b: yes}
      - {a: tomcat9-admin, b: yes}
- name: Continuous Download and Continuous Build
  hosts: DevServer
  tasks:
   - name: Continuous Download
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: /tmp/mygit
   - name: Continuous Build and creating artifact
     shell: cd /tmp/mygit;mvn package
- name: Deploying artifacts to QAServer
  hosts: QAServer
  tasks:
   - name: Copying artifact into Tomcat of QAServer
     copy:
      src: /tmp/mygit
      dest: /var/lib/tomcat9/webapps/qaapp.war
   - name: Downloading selenium program into QA Server
     git: 
      repo: https://github.com/intelliqittrainings/FunctionalTesting.git
      dest: /tmp/test-git
   - name: Executing selenium programs
     shell: java -jar /tmp/test-git/testing.jar
- name: Deploying artifacts to ProdServer
  hosts: ProdServer
  tasks:
   - name: Copy artifacts from DevServer to ProdServer
     copy:
      src: /tmp/mygit/webapp/target/webapp.war
      dest: /var/lib/tomcat9/webapps/prodapp.war 
   - name: Displaying messages
     debug: 
      msg: "CI-CD has been executed successfully" 


...
