---
- name: Configuring Tomcat9
  hosts: all
  tasks:
   - name: Installing Tomcat9
     apt:
      name: tomcat9
      state: present
      update_cache: Yes
   - name: Installing Tomcat9-admin
     apt:
      state: present
      update_cache: yes
   - name: Adding Username & password
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Restarting Tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: Replacing port numbers
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restarting Tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: Pausing for 2 minutes
     pause:
      minutes: 2
   - name: Check response of tomcat on server1
     uri:
      url: http://172.31.0.104:9090
      status_code: 200
   - name: Check response of tomcat on server2
     uri:
      url: http://172.31.3.241:9090
      status_code: 200


...
