---
- name: Checking if a directory name as d1 is present if not than creating a file name as d1 
  hosts: all
  tasks:
   - name: Checking if a directory d1 is present or not
     stat:
      path: /home/ubuntu/d1
     register: a
   - name: Displaying the output from var a
     debug:
      var: a
   - name: Creating file d1 if dir d1 is not present
     file:
      name: d1
      dest: /home/ubuntu
      state: touch
     when: a.stat.exists == false

  











...
