
- name: Implementing Loops
  hosts: all
  vars:
   - name: Installing Software apps
     apt: 
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - tree
      - git
      - ant











