---
- name: Configuring muliple software using loops
  hosts: all
  tasks:
   - name: Installing multiple softwae pack
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree, b: absent, c: yes}
      - {a: git, b: present, c: no}
      - {a: maven, b: present, c: no}






...
