---
- name: Setting up Jenkins Server 
  hosts: jenkinsserver
  tasks:
   - name: Installing necessary s/w
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk, b: yes }
      - {a: git, b: no}
      - {a: maven, b: no}
   - name: Downloading jenkins file
     get_url:
      url: https://get.jenkins.io/war-stable/2.289.2/jenkins.war
      dest: /tmp
- name: Setting up Tomcat in qa and prod server
  hosts: servers
  tasks:
   - name: installing_tomcat9
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9, b: yes}
      - {a: tomcat9-admin, b: yes}
     notify: checking url response
   - name: copying tomcat9 users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
     notify: restarting tomcat9
  handlers:
   - name: restarting tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: checking url response
     uri:
      url: "{{items}}"
      status_code: 200
     with_items:
      - http://172.31.0.104:8080
      - http://172.31.3.241:8080


     
      
    
      
...
